export const CHANGE_TYPE = "CHANGE_TYPE";
export const GET_TYPES_SUCCESS = "GET_TYPES_SUCCESS";
export const GET_TYPES_ERROR = "GET_TYPES_ERROR";
export const GET_TYPES_START = "GET_TYPES_START";

export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_START = "GET_POKEMONS_START";
export const GET_POKEMONS_COUNT = "GET_POKEMONS_COUNT";