export const CHANGE_TYPE = "CHANGE_TYPE";
export const GET_TYPES_SUCCESS = "GET_TYPES_SUCCESS";
export const GET_TYPES_ERROR = "GET_TYPES_ERROR";
export const GET_TYPES_START = "GET_TYPES_START";

export const GET_POKEMONS_SUCCESS = "GET_POKEMONS_SUCCESS";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_START = "GET_POKEMONS_START";
export const GET_POKEMONS_COUNT = "GET_POKEMONS_COUNT";

export const ADD_TO_INVENTORY = "ADD_TO_INVENTORY";
export const REMOVE_FROM_INVENTORY = "REMOVE_FROM_INVENTORY";

export const ADD_OR_REMOVE_FAV = "ADD_OR_REMOVE_FAV";

export const GET_POKEMON_SUCCESS = "GET_POKEMON_SUCCESS";
export const GET_POKEMON_FAMILY_SUCCESS = "GET_POKEMON_FAMILY_SUCCESS";
export const GET_POKEMON_ERROR = "GET_POKEMON_ERROR";
export const GET_POKEMON_CLEAR = "GET_POKEMON_CLEAR";